#!/usr/bin/env python3
"""Build the local chapter player and a real 390px iframe preview."""
import hashlib
import json
from runtime import BASE

D=json.loads((BASE/'timeline.json').read_text())
media=BASE/'renders/activation-functions-v6.mp4'
token=hashlib.sha256(media.read_bytes()).hexdigest()[:16]
minutes=round(D['duration'])//60;seconds=round(D['duration'])%60
data={'duration':D['duration'],'fps':D['fps'],'chapters':D['chapters'],'scenes':[{k:s[k] for k in ['id','chapter','title','start','end']} for s in D['scenes']]}
template=r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>激活函数 · 我的深度学习之路</title><style>
:root{color-scheme:light;--ink:#44382e;--paper:#fff7e6;--teal:#246e65;--coral:#ae4937}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:"PingFang SC","Hiragino Sans GB",system-ui,sans-serif}main{max-width:1060px;margin:34px auto;padding:0 24px}header{margin-bottom:26px}h1{font-size:31px;line-height:1.4;margin:0 0 8px}header p{margin:0;line-height:1.65;color:#625649}.layout{display:grid;grid-template-columns:360px 1fr;gap:36px;align-items:start}.player{border:2px solid var(--ink);border-radius:18px;overflow:hidden;background:#fffdf5;box-shadow:7px 7px 0 #e3d5b9}video{display:block;width:100%;aspect-ratio:9/16;background:var(--paper);object-fit:contain}.seek-area{padding:14px 13px 10px;border-bottom:1px solid #d5c5a6}.main-chapters{display:flex;gap:5px;margin-bottom:9px}button{font:inherit;color:var(--ink);background:#fffdf5;border:1px solid #ae9a7a;border-radius:8px;cursor:pointer}button:hover{background:#efe4ce}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid var(--teal);outline-offset:3px}.main-chapters button{flex:1;padding:8px 3px;font-size:12px}.main-chapters button[aria-current=true]{background:#dceae2;border-color:var(--teal)}input[type=range]{width:100%;accent-color:var(--teal)}.clock{display:flex;justify-content:space-between;font-size:12px;margin:5px 0;gap:10px}.now{font-size:13px;line-height:1.5;min-height:21px}.actions{padding:10px;display:flex;flex-wrap:wrap;gap:7px}.actions button,.actions a{font-size:12px;line-height:1.4;padding:8px;text-decoration:none;border-radius:8px}.actions a{color:var(--ink);border:1px solid #ae9a7a}aside h2{font-size:21px;margin:3px 0 10px}.hint{font-size:14px;line-height:1.75;margin:0 0 18px}.group{font-size:15px;margin:23px 0 9px;display:flex;justify-content:space-between}.sections{display:grid;grid-template-columns:1fr 1fr;gap:9px}.section{min-height:83px;padding:11px;text-align:left;font-size:13px;line-height:1.6}.section small{display:block;color:#645746;margin-top:4px}.section[aria-current=true]{background:#dceae2;border:2px solid var(--teal)}.reading{border-top:1px solid #d5c5a6;padding-top:18px;margin-top:23px;display:flex;gap:14px;flex-wrap:wrap;font-size:13px}a{color:var(--teal)}.error{padding:12px;color:var(--coral)}#qa-status{font-size:11px;color:#625649;padding:0 12px 10px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:760px){main{margin:21px auto;padding:0 16px}.layout{grid-template-columns:1fr;gap:28px}.player{width:100%;max-width:390px;margin:auto}h1{font-size:25px}.sections{grid-template-columns:1fr 1fr}aside{min-width:0}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style></head><body><main><header><h1>一百层以上的网络，为什么还分不开四个点？</h1><p>我的深度学习之路 · 约 __MINUTES__ 分 __SECONDS__ 秒看懂激活函数<br>从非线性与梯度，走到大模型里的门控、稳定性与计算成本。</p></header><div class="layout"><section class="player" aria-label="激活函数视频播放器"><div class="seek-area"><nav class="main-chapters" aria-label="三部分内容"></nav><label for="seek" class="sr-only">拖动视频进度</label><input id="seek" type="range" min="0" max="__DURATION__" value="0" step="1"><div class="clock"><span id="time">00:00 / __CLOCK__</span><span>← → 跳转 5 秒</span></div><div class="now" id="now">01 · 一百层网络，分不开四个点？</div></div><video id="film" controls playsinline preload="metadata" src="renders/activation-functions-v6.mp4?v=__TOKEN__" poster="assets/poster.jpg"></video><div class="actions"><button id="play" type="button">播放</button><button id="restart" type="button">从头连续播放</button><a href="renders/activation-functions-v6.mp4" download>下载 MP4</a></div><div id="error" class="error" hidden></div><div id="qa-status" aria-live="polite"></div></section><aside><h2>跟着三个问题理解激活函数</h2><p class="hint">先看为什么网络需要拐弯，再看这个拐弯如何演化，最后了解今天值得追踪的研究。点击章节或拖动进度条，可以回到任何一个小节。</p><div id="sections"></div><div class="reading"><a href="../../001-introduction.md">阅读全文与论文 ↗</a><a href="mobile-preview.html">手机排版预览 ↗</a><a href="https://github.com/shikanon/my-deep-learning-journey" target="_blank" rel="noopener">关注 GitHub 项目 ↗</a></div></aside></div></main><script>
const DATA=__DATA__,film=document.querySelector('#film'),seek=document.querySelector('#seek'),play=document.querySelector('#play');
const fmt=t=>{t=Math.floor(Math.max(0,t));return String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0')};
let run=null;const pageErrors=[];
function sample(){return {currentSrc:film.currentSrc,duration:film.duration,currentTime:film.currentTime,readyState:film.readyState,paused:film.paused,ended:film.ended,muted:film.muted,volume:film.volume,playbackRate:film.playbackRate,mediaError:film.error?{code:film.error.code,message:film.error.message}:null,pageErrors:[...pageErrors]}}
async function saveRun(){if(!run)return;const payload={...run,...sample()};try{await fetch('/__qa/playback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}catch(e){pageErrors.push(String(e))}}
window.addEventListener('error',e=>pageErrors.push(String(e.message)));window.addEventListener('unhandledrejection',e=>pageErrors.push(String(e.reason)));
function chapterTime(t){return Math.ceil(t*DATA.fps)/DATA.fps+.005}
function jump(t){film.currentTime=Math.max(0,Math.min(t,DATA.duration));sync()}
function sync(){const t=film.currentTime;seek.value=t;document.querySelector('#time').textContent=fmt(t)+' / '+fmt(film.duration||DATA.duration);const s=DATA.scenes.reduce((last,s)=>t+.0001>=s.start?s:last,DATA.scenes[0]);document.querySelector('#now').textContent=s.id.slice(1)+' · '+s.title.replaceAll('\n',' ');seek.setAttribute('aria-valuetext',fmt(t)+'，'+s.title.replaceAll('\n',' '));document.querySelectorAll('.section').forEach(b=>b.setAttribute('aria-current',b.dataset.scene===s.id?'true':'false'));document.querySelectorAll('.main-chapters button').forEach(b=>b.setAttribute('aria-current',b.dataset.chapter===s.chapter?'true':'false'));play.textContent=film.paused?'播放':'暂停';if(run&&!run.finished){run.observations++;if(film.playbackRate!==1)run.rateChanged=true;if(film.muted||film.volume===0)run.notAudible=true;}}
DATA.chapters.forEach(c=>{const b=document.createElement('button');b.type='button';b.textContent=c.title;b.dataset.chapter=c.id;b.setAttribute('aria-label','跳转大章：'+c.title);b.onclick=()=>jump(chapterTime(c.start));document.querySelector('.main-chapters').append(b)});
for(const c of [...DATA.chapters,{id:'cta',title:'一起学习'}]){const group=document.createElement('div');group.className='group';group.textContent=c.title+(c.share?' · '+Math.round(c.share*100)+'%':'');document.querySelector('#sections').append(group);const grid=document.createElement('div');grid.className='sections';document.querySelector('#sections').append(grid);DATA.scenes.filter(s=>s.chapter===c.id).forEach(s=>{const b=document.createElement('button');b.type='button';b.className='section';b.dataset.scene=s.id;b.setAttribute('aria-label','跳转小节 '+s.id.slice(1)+'：'+s.title.replaceAll('\n',' '));const title=document.createElement('span');title.textContent=s.id.slice(1)+' · '+s.title.replaceAll('\n',' ');const time=document.createElement('small');time.textContent=fmt(s.start)+' — '+fmt(s.end);b.append(title,time);b.onclick=()=>jump(chapterTime(s.start));grid.append(b)})}
seek.addEventListener('input',()=>jump(Number(seek.value)));['timeupdate','seeked','loadedmetadata','play','pause','ended'].forEach(e=>film.addEventListener(e,sync));
film.addEventListener('seeking',()=>{if(run&&!run.finished)run.seekEvents++});film.addEventListener('waiting',()=>{if(run&&!run.finished)run.waitingEvents++});film.addEventListener('pause',()=>{if(run&&!run.finished&&!film.ended)run.pauseEvents++});film.addEventListener('error',()=>{document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='视频加载失败，请通过下载入口观看，或重新启动本地播放器。';saveRun()});
film.addEventListener('ended',async()=>{if(run){run.finished=true;run.elapsedWallSeconds=(performance.now()-run.startedAtMs)/1000;await saveRun();document.querySelector('#qa-status').textContent='已连续播放到结束';}});
play.onclick=async()=>{try{if(film.paused)await film.play();else film.pause()}catch(e){pageErrors.push(String(e))}};
document.querySelector('#restart').onclick=async()=>{film.pause();run=null;if(film.currentTime>.005){await new Promise(resolve=>{film.addEventListener('seeked',resolve,{once:true});film.currentTime=0})}run={id:crypto.randomUUID(),startedAtMs:performance.now(),startedAtVideoTime:film.currentTime,seekEvents:0,pauseEvents:0,waitingEvents:0,observations:0,rateChanged:false,notAudible:false,finished:false};film.playbackRate=1;film.muted=false;film.volume=1;document.querySelector('#qa-status').textContent='从头连续播放中';try{await film.play()}catch(e){pageErrors.push(String(e));await saveRun()}};
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.key==='ArrowRight'){e.preventDefault();jump(film.currentTime+5)}if(e.key==='ArrowLeft'){e.preventDefault();jump(film.currentTime-5)}if(e.key==='Home'){e.preventDefault();jump(0)}if(e.key==='End'){e.preventDefault();jump(DATA.duration-.05)}});
sync();
</script></body></html>'''
template=template.replace('__MINUTES__',str(minutes)).replace('__SECONDS__',str(seconds)).replace('__CLOCK__',f'{minutes:02}:{seconds:02}').replace('__TOKEN__',token).replace('__DURATION__',str(D['duration'])).replace('__DATA__',json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c'))
(BASE/'watch.html').write_text(template+'\n')
(BASE/'mobile-preview.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>390px 手机预览 · 激活函数</title><style>body{margin:0;background:#e7dbc2;font-family:system-ui;color:#44382e}h1{font-size:19px;text-align:center;margin:20px}iframe{display:block;width:390px;height:844px;max-width:100%;margin:20px auto;border:2px solid #44382e;border-radius:20px;background:#fff7e6}</style><h1>390 × 844 手机排版预览</h1><iframe title="手机播放器" src="watch.html"></iframe></html>\n''')
print(json.dumps({'player':'watch.html','media_hash_token':token,'sections':len(data['scenes'])},ensure_ascii=False))
