"""Build the portable, frame-scrubbable preview and sync it to video assets."""
import json,shutil
from pathlib import Path
B=Path(__file__).resolve().parent;L=B.parents[3]/'assets/手绘形象/shikanon-animation-v2'
M=json.loads((L/'manifest.json').read_text())
page=r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>shikanon · 作者手绘动作库</title><style>
*{box-sizing:border-box}body{margin:0;color:#46392f;background:#fff7e4;font-family:"PingFang SC","Hiragino Sans GB",sans-serif}main{max-width:1040px;margin:32px auto;padding:0 24px}header{border-bottom:2px solid #d2c7ae;padding-bottom:22px;margin-bottom:26px;display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:29px;margin:0 0 9px}p{font-size:14px;line-height:1.7;color:#66574a;margin:0}a{color:#46392f;text-underline-offset:4px}button,select{border:1.5px solid #46392f;border-radius:9px;padding:9px 13px;background:#fffcf3;color:#46392f;font-size:14px;cursor:pointer}button[aria-pressed=true],#play{background:#edcd74}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #73a6a3;outline-offset:3px}.layout{display:grid;grid-template-columns:340px 1fr;gap:40px}.stage{border:2px solid #46392f;border-radius:18px;overflow:hidden;box-shadow:6px 7px 0 #edcd74;background-color:#fffcf3;background-image:linear-gradient(45deg,#eee6d7 25%,transparent 25%),linear-gradient(-45deg,#eee6d7 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#eee6d7 75%),linear-gradient(-45deg,transparent 75%,#eee6d7 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}canvas{width:100%;height:auto;display:block}.controls{display:flex;gap:9px;margin:18px 0 12px;align-items:center;flex-wrap:wrap}.frame-control{width:100%;accent-color:#ed826a}.status{display:flex;justify-content:space-between;font-size:13px;margin:10px 0}.tabs{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 20px}.explain{background:#fffcf3;border:1.5px solid #d2c7ae;border-radius:14px;padding:20px;margin-bottom:21px}h2{font-size:22px;margin:0 0 11px}.meta{font-size:13px;line-height:1.9}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:32px 0 26px}.card{border:1.5px solid #d2c7ae;border-radius:13px;background:#fffcf3;overflow:hidden;text-align:center;cursor:pointer}.card img{width:100%;display:block}.card span{font-size:13px;display:block;padding-bottom:12px}.code{padding:17px;border-radius:12px;background:#f0e7d3;font-size:12px;line-height:1.8;overflow-x:auto}.foot{border-top:1px solid #d2c7ae;padding-top:18px;font-size:12px}.error{color:#a13c27}body.dark .stage{background:#25313b;background-image:linear-gradient(45deg,#303e49 25%,transparent 25%),linear-gradient(-45deg,#303e49 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#303e49 75%),linear-gradient(-45deg,transparent 75%,#303e49 75%)}@media(max-width:740px){main{margin:22px auto;padding:0 18px}header{display:block}header a{display:block;margin-top:10px}.layout{grid-template-columns:1fr;gap:30px}.preview{max-width:340px;width:100%;margin:auto}.cards{grid-template-columns:repeat(3,1fr)}h1{font-size:26px}}
</style></head><body><main><header><div><h1>人物稳住，动作更清楚</h1><p>shikanon · 儿童彩铅手绘 · 七组透明序列帧</p></div><a href="README.md">素材与复用说明 ↗</a></header><div class="layout"><section class="preview"><div class="stage"><canvas id="stage" width="384" height="576" aria-label="作者序列帧动画预览"></canvas></div><div class="controls"><button id="play" type="button">暂停</button><label>速度 <select id="speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option></select></label><button id="theme" type="button">深色背景</button></div><label for="frame" class="meta">拖动查看每一帧</label><input class="frame-control" id="frame" aria-label="动画帧" type="range" min="0" max="11" step="1" value="0"><div class="status"><span id="counter">帧 01 / 12</span><span>10 fps · 循环</span></div></section><section><nav class="tabs" aria-label="动作选择"></nav><article class="explain"><h2 id="name"></h2><p id="purpose"></p></article><div class="meta">每组 12 帧 · 384 × 576 · PNG 真透明<br>头部、腰线、脚底共用一个底稿<br>脚底锚点：192, 548<br>人物轮廓稳定，嘴型、眼睛与手臂随帧变化<br>已有图集与单帧均可直接取用</div><p class="meta" style="margin-top:20px"><a id="atlas" download>下载当前图集</a> · <a href="manifest.json" download>下载动作配置</a> · <a id="webp" download>下载动画预览</a></p><pre class="code">const frame = action.frames[index];
ctx.drawImage(atlas,
  ...frame.atlas_rect,  // 当前帧在图集中的位置
  x - 192, y - 548, 384, 576);
// x、y 为人物脚底锚点；切换 action 即切换动作</pre><p id="error" class="error" hidden></p></section></div><div class="cards" aria-label="七组动作同时预览"></div><p class="foot">我的深度学习之路 · 素材已缓存，可供后续视频复用。讲解嘴型为节奏动画，未逐音素对齐配音。</p></main><script>
const LIB=__MANIFEST__;
const LABELS={talk:['讲解','随说话节奏变换嘴型、开掌讲解，偶尔眨眼。'], 'point-right':['指向','伸手指向评分规则、曲线与回答卡片，让视线跟着重点走。'],think:['思考','抬手托腮、看向上方并眨眼，用于问题、阈值与研究取舍。'],celebrate:['领悟','握拳抬至脸侧、开心眨眼，用于总结与理解后的反馈。'],wave:['挥手','抬手、摆动手腕并微笑，用于欢迎与项目片尾。']};
LABELS['teach-pointer']=['教棍','教棍跟随手掌转动，用于曲线、反向传播与师生讲解。'];LABELS['think-question']=['思考问号','同一思考动作，头顶固定问号提示当前疑问。'];
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),slider=document.getElementById('frame');
let action='talk',index=0,playing=true,origin=performance.now(),rate=1;
const images={};let ready=0;
function draw(){const m=LIB.actions[action],im=images[action];if(!im?.complete||!im.naturalWidth)return;const r=m.frames[index].atlas_rect;ctx.clearRect(0,0,384,576);ctx.drawImage(im,...r,0,0,384,576);slider.value=index;document.getElementById('counter').textContent='帧 '+String(index+1).padStart(2,'0')+' / 12';canvas.dataset.action=action;canvas.dataset.frame=index;}
function choose(key){action=key;index=0;origin=performance.now();document.getElementById('name').textContent=LABELS[key][0];document.getElementById('purpose').textContent=LABELS[key][1];document.querySelectorAll('.tabs button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.action===key));document.getElementById('atlas').href=LIB.actions[key].atlas;document.getElementById('webp').href=LIB.actions[key].preview;draw();}
Object.entries(LIB.actions).forEach(([key,m])=>{const image=new Image;image.onload=()=>{ready++;canvas.dataset.loaded=ready;draw()};image.onerror=()=>{const e=document.getElementById('error');e.hidden=false;e.textContent='图集未加载，请保留完整素材文件夹。'};image.src=m.atlas;images[key]=image;const b=document.createElement('button');b.type='button';b.dataset.action=key;b.textContent=LABELS[key][0];b.onclick=()=>choose(key);document.querySelector('.tabs').append(b);const card=document.createElement('button');card.type='button';card.className='card';card.setAttribute('aria-label','预览'+LABELS[key][0]);card.innerHTML='<img src="'+m.preview+'" alt="'+LABELS[key][0]+'动画预览"><span>'+LABELS[key][0]+' · 12 帧</span>';card.onclick=()=>choose(key);document.querySelector('.cards').append(card)});
document.getElementById('play').onclick=()=>{playing=!playing;document.getElementById('play').textContent=playing?'暂停':'播放';origin=performance.now()-index/10/rate*1000};
slider.oninput=()=>{playing=false;document.getElementById('play').textContent='播放';index=Number(slider.value);draw()};
document.getElementById('speed').onchange=e=>{rate=Number(e.target.value);origin=performance.now()-index/10/rate*1000};
document.getElementById('theme').onclick=e=>{document.body.classList.toggle('dark');e.target.textContent=document.body.classList.contains('dark')?'浅色背景':'深色背景'};
function tick(now){if(playing){index=Math.floor((now-origin)/1000*10*rate)%12;draw()}requestAnimationFrame(tick)}choose('talk');requestAnimationFrame(tick);
</script></body></html>'''
(L/'preview.html').write_text(page.replace('__MANIFEST__',json.dumps(M,ensure_ascii=False,separators=(',',':'))))
shutil.copytree(L,B/'assets/author-animation',dirs_exist_ok=True)
print('Portable library preview saved and synced')
